name: Release Packages

on:
  push:
    branches:
      - 'release-please--*'
    tags:
      - '*'

jobs:
  release-maven-artifacts:
    name: Release all Maven artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          if [ "${{ github.ref_type }}" == "branch" ]; then
            versionName="$(jq -c -r -M ".." .release-please-manifest.json | tail -1)-SNAPSHOT"
          else
            echo "versionName not set type=${{github.ref_type}}, using github.ref_name=${{github.ref_name}}"
            versionName=${{ github.ref_name }}
          fi
          echo "" >> gradle.properties
          echo "VERSION_NAME=$versionName" >> gradle.properties
          echo "mavenCentralUsername=${{ secrets.MAVEN_USERNAME }}" >> gradle.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_PASSWORD }}" >> gradle.properties
          echo "signingInMemoryKeyId=${{ secrets.SIGNING_KEY_ID }}" >> gradle.properties
          echo "signingInMemoryKeyPassword=${{ secrets.SIGNING_KEY_PASS }}" >> gradle.properties
          echo "signingInMemoryKey=${{ secrets.SIGNING_KEY }}" >> gradle.properties
      - run: |
          if [ "${{ github.ref_type }}" == "branch" ]; then
            ./gradlew publishAllPublicationsToMavenCentralRepository --no-configuration-cache
          else
            ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
          fi