name: Release Packages

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build-and-release:
    name: Java Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dragapult-app/build/distributions/dragapult-app-shadow.zip
